# <font color='blue'>Manipulação de Dados em Python com NumPy</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python usado neste Jupyter Notebook:', python_version())

Versão da Linguagem Python usado neste Jupyter Notebook: 3.9.12


In [2]:
# Importando o módulo Numpy
import numpy as np

# Transposição e Reshaping de Arrays

In [3]:
array1 = np.array([[65, 23, 19], [41, 87, 10]])

In [5]:
array1

array([[65, 23, 19],
       [41, 87, 10]])

In [6]:
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [7]:
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

## Broadcasting

In [8]:
array2 = np.array([[33, 34, 35]])

In [9]:
array2

array([[33, 34, 35]])

In [10]:
array2.T

array([[33],
       [34],
       [35]])

In [11]:
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

## Transformando Matrizes em Vetores

In [12]:
array3 = np.array([np.arange(1,6), np.arange(10,15)])

In [13]:
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [14]:
array3.ndim

2

In [15]:
array3.shape

(2, 5)

In [16]:
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [17]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

## Operadores Lógicos

In [18]:
np.random.seed(100)
array4 = np.random.randint(1, 10, size = (4,4))

In [19]:
array4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [25]:
np.any((array4 % 7) == 0)

False

In [31]:
np.all(array4 <= 9)

True

In [32]:
# Retorne a linha onde o elemento de índice 1 na coluna seja maior que 2 e menor que 9
np.where(np.logical_and(array4[:,1] > 2, array4[:,1] < 9))

(array([2]),)

In [33]:
# Mesmo resultado que a linha anterior
np.intersect1d(np.where(array4[:,1] > 2), np.where(array4[:,1] < 9))

array([2])

In [34]:
array4[2]

array([6, 3, 3, 3])

## Reshaping e Ordenação de Arrays

In [35]:
array5 = np.arange(1,16)

In [36]:
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
array5.ndim

1

In [38]:
array5.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [48]:
array7 = np.array([[3,2],[10,-1]])

In [49]:
array7

array([[ 3,  2],
       [10, -1]])

In [50]:
# Ordenando por linhas
array7.sort(axis = 1)

In [51]:
array7

array([[ 2,  3],
       [-1, 10]])

In [52]:
array8 = np.array([[3,2],[10,-1]])

In [53]:
array8

array([[ 3,  2],
       [10, -1]])

In [54]:
# Ordenando por colunas
array8.sort(axis = 0)

In [55]:
array8

array([[ 3, -1],
       [10,  2]])